///////////////////////////////////////////////////////////////////////////////
// EncoderVelocityTestingInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "EncoderVelocityTestingServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
