///////////////////////////////////////////////////////////////////////////////
// EncoderVelocityTestingServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_EncoderVelocityTesting = 0x3F000000;
#define SRVNAME_ENCODERVELOCITYTESTING "EncoderVelocityTesting"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_EncoderVelocityTestingCModule = {0x3d435ccc,0x1f14,0x424c,{0xba,0x2b,0xf1,0xc2,0x4e,0x04,0x37,0x51}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ModulePreviousEncoderPosition = 0x00000001;
const PTCID PID_ModuleBadDataCounter = 0x00000002;
const PTCID PID_ModuleStarted = 0x00000003;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _ModuleInputs
{
	LONG CurrentEncoderPosition;
} ModuleInputs, *PModuleInputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_ModuleInputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
