///////////////////////////////////////////////////////////////////////////////
// EncoderVelocityTestingServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_EncoderVelocityTesting = 0x3F000000;
#define SRVNAME_ENCODERVELOCITYTESTING "EncoderVelocityTesting"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_EncoderVelocityTestingCModule = {0x3d435ccc,0x1f14,0x424c,{0xba,0x2b,0xf1,0xc2,0x4e,0x04,0x37,0x51}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
