///////////////////////////////////////////////////////////////////////////////
// EncoderVelocityTestingClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "EncoderVelocityTestingClassFactory.h"
#include "EncoderVelocityTestingServices.h"
#include "EncoderVelocityTestingVersion.h"
#include "Module.h"

BEGIN_CLASS_MAP(CEncoderVelocityTestingClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_EncoderVelocityTesting, CID_EncoderVelocityTestingCModule, SRVNAME_ENCODERVELOCITYTESTING "!CModule", CModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CEncoderVelocityTestingClassFactory::CEncoderVelocityTestingClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_ENCODERVELOCITYTESTING));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(EncoderVelocityTesting));
#endif //defined(TCDBG_UNIT_VERSION)
}

